// Auto-generated by ResourcePathGenerator. Do not edit manually.
namespace PlatformCore.Services.Factory
{
	public static class ResourcePaths
	{
		public static class Characters
		{
			public const string Player = "Characters/Player";
		}
		public static class Main
		{
			public const string CinemachineCamera = "Main/CinemachineCamera";
		}
		public static class UI
		{
			public const string PauseMenu = "UI/PauseMenu";
		}
		public const string DOTweenSettings = "DOTweenSettings";
	}
}
