#if UNITY_EDITOR
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace PlatformCore.EditorTools
{
    public static class ResourcePathGenerator
    {
        private const string OutputPath = "Assets/PlatformCore/Services/Factory/ResourcePaths.cs";
        private const string Namespace = "PlatformCore.Services.Factory";

        [MenuItem("Tools/Generate/Resource Paths")]
        public static void Generate()
        {
            string resourcesPath = Path.Combine(Application.dataPath, "Resources");
            if (!Directory.Exists(resourcesPath))
            {
                Debug.LogWarning("⚠️ Resources folder not found in project.");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by ResourcePathGenerator. Do not edit manually.");
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("\tpublic static class ResourcePaths");
            sb.AppendLine("\t{");

            GenerateRecursive(sb, resourcesPath, 2);

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            Debug.Log("✅ ResourcePaths.cs successfully regenerated.");
        }

        private static void GenerateRecursive(StringBuilder sb, string currentPath, int indentLevel)
        {
            string indent = new string('\t', indentLevel);

            // Подпапки
            foreach (var dir in Directory.GetDirectories(currentPath))
            {
                string dirName = Path.GetFileName(dir);
                sb.AppendLine($"{indent}public static class {dirName}");
                sb.AppendLine($"{indent}{{");
                GenerateRecursive(sb, dir, indentLevel + 1);
                sb.AppendLine($"{indent}}}");
            }

            // Файлы
            var files = Directory.GetFiles(currentPath, "*.*", SearchOption.TopDirectoryOnly)
                .Where(f => !f.EndsWith(".meta"));

            foreach (var file in files)
            {
                string fileName = Path.GetFileNameWithoutExtension(file);

                // Формируем относительный путь от Resources/
                string relPath = file
                    .Replace(Application.dataPath + Path.DirectorySeparatorChar + "Resources" + Path.DirectorySeparatorChar, "")
                    .Replace("\\", "/");

                // Убираем расширение
                relPath = relPath.Substring(0, relPath.LastIndexOf('.'));

                sb.AppendLine($"{indent}public const string {fileName} = \"{relPath}\";");
            }
        }
    }
}
#endif
